"""Community contribution — share evolution learnings via GitHub PR.

Uses the GitHub API to fork the main repo (if needed), create a branch,
commit evolved code + metadata, and open a pull request.

The PR includes:
  - community/contributions/{instance_id}.json  (metadata + archive)
  - community/evolved/{instance_id}/*.py        (actual evolved code)

This closes the federated learning loop: evolved code that passed sandbox
validation on one instance becomes available to all other instances.
"""

from __future__ import annotations

import json
import base64
from datetime import datetime

import httpx

from agos.config import settings

GITHUB_API = "https://api.github.com"

# Hardcoded: ALL instances worldwide share learnings to the same central repo.
# This is intentional — community contributions must converge to one place.
UPSTREAM_OWNER = "opensculpt"
UPSTREAM_REPO = "opensculpt"


class ContributionError(Exception):
    """Failed to create a community contribution."""


async def share_knowledge(
    github_token: str,
) -> dict:
    """Share anonymized knowledge patterns via GitHub PR.

    The PR targets opensculpt/opensculpt — hardcoded.

    Shares ONLY anonymized knowledge (constraints, resolutions, demand
    categories) — NO code, NO paths, NO private data. Uses the curator's
    existing anonymization pipeline.

    For sharing CODE, users open PRs from their fork (standard git workflow).

    Returns {"pr_url": "...", "branch": "...", "files_committed": N}.
    Raises ContributionError on failure.
    """
    import hashlib
    from pathlib import Path

    owner = UPSTREAM_OWNER
    repo = UPSTREAM_REPO

    # Generate anonymized knowledge via curator
    from agos.evolution.curator import export_contribution as curator_export
    contrib_dir = curator_export()

    # Anonymized instance ID
    from agos.evolution.state import EvolutionState
    state = EvolutionState()
    state.load()
    anon_id = hashlib.sha256(state.data.instance_id.encode()).hexdigest()[:12]
    timestamp = datetime.utcnow().strftime("%Y%m%d-%H%M%S")
    branch_name = f"knowledge/{anon_id}/{timestamp}"

    headers = {
        "Authorization": f"token {github_token}",
        "Accept": "application/vnd.github.v3+json",
    }

    async with httpx.AsyncClient(
        timeout=30, headers=headers, follow_redirects=True
    ) as client:
        fork_user = await _get_authenticated_user(client)
        await _ensure_fork(client, owner, repo)
        default_sha = await _get_default_branch_sha(client, fork_user, repo)
        await _create_branch(client, fork_user, repo, branch_name, default_sha)

        # Build file list from curator's anonymized output
        files: list[tuple[str, str]] = []
        prefix = f"community/knowledge/{anon_id}"

        if contrib_dir.exists():
            for f in sorted(contrib_dir.rglob("*")):
                if not f.is_file():
                    continue
                rel = f.relative_to(contrib_dir).as_posix()
                content = f.read_text(encoding="utf-8")
                files.append((f"{prefix}/{rel}", content))

        if not files:
            raise ContributionError("No knowledge to share (constraints/resolutions empty)")

        await _commit_tree(
            client, fork_user, repo, branch_name, default_sha,
            files=files,
            message=f"Add anonymized knowledge patterns from {anon_id}",
        )

        pr_title = f"[Knowledge] {len(files)} anonymized patterns from {anon_id}"
        pr_body = _build_pr_body(anon_id, len(files))

        pr_url = await _create_pr(
            client, owner, repo,
            head=f"{fork_user}:{branch_name}",
            base="main",
            title=pr_title,
            body=pr_body,
        )

    return {
        "pr_url": pr_url,
        "branch": branch_name,
        "files_committed": len(files),
    }


# Keep old name as alias for backward compatibility
share_learnings = share_knowledge

def _build_pr_body(anon_id: str, n_files: int) -> str:
    """Build PR body for anonymized knowledge contribution."""
    return (
        f"## Anonymized Knowledge Contribution\n\n"
        f"- **Anonymous ID:** `{anon_id}`\n"
        f"- **Files:** {n_files} (constraints, resolutions, demand summaries)\n\n"
        f"This PR contains anonymized knowledge patterns learned by an OpenSculpt instance.\n"
        f"All IPs, paths, API keys, and identifiable information have been stripped.\n\n"
        f"**No code is included.** For code contributions, submit a PR from your fork.\n\n"
        f"---\n*Auto-generated by OpenSculpt evolution engine.*\n"
    )


# ── GitHub API helpers ───────────────────────────────────────────


async def _get_authenticated_user(client: httpx.AsyncClient) -> str:
    resp = await client.get(f"{GITHUB_API}/user")
    if resp.status_code != 200:
        raise ContributionError(
            f"Auth failed ({resp.status_code}): check your GitHub token"
        )
    return resp.json()["login"]


async def _ensure_fork(
    client: httpx.AsyncClient, owner: str, repo: str
) -> None:
    resp = await client.post(f"{GITHUB_API}/repos/{owner}/{repo}/forks")
    if resp.status_code not in (200, 202):
        raise ContributionError(f"Fork failed: {resp.status_code}")


async def _get_default_branch_sha(
    client: httpx.AsyncClient, owner: str, repo: str
) -> str:
    resp = await client.get(f"{GITHUB_API}/repos/{owner}/{repo}")
    if resp.status_code != 200:
        raise ContributionError(f"Repo not found: {resp.status_code}")
    default_branch = resp.json().get("default_branch", "main")
    ref = await client.get(
        f"{GITHUB_API}/repos/{owner}/{repo}/git/ref/heads/{default_branch}"
    )
    if ref.status_code != 200:
        raise ContributionError(f"Branch ref failed: {ref.status_code}")
    return ref.json()["object"]["sha"]


async def _create_branch(
    client: httpx.AsyncClient, owner: str, repo: str,
    branch: str, sha: str,
) -> None:
    resp = await client.post(
        f"{GITHUB_API}/repos/{owner}/{repo}/git/refs",
        json={"ref": f"refs/heads/{branch}", "sha": sha},
    )
    if resp.status_code not in (200, 201):
        raise ContributionError(f"Branch creation failed: {resp.status_code}")


async def _commit_tree(
    client: httpx.AsyncClient, owner: str, repo: str,
    branch: str, base_sha: str,
    files: list[tuple[str, str]],
    message: str,
) -> str:
    """Commit multiple files in a single Git tree operation.

    Uses the Git Data API (trees + commits) instead of Contents API
    so all files land in one atomic commit.

    Returns the new commit SHA.
    """
    # Step 1: Create blobs for each file
    tree_items = []
    for path, content in files:
        blob_resp = await client.post(
            f"{GITHUB_API}/repos/{owner}/{repo}/git/blobs",
            json={
                "content": base64.b64encode(content.encode("utf-8")).decode("ascii"),
                "encoding": "base64",
            },
        )
        if blob_resp.status_code not in (200, 201):
            raise ContributionError(
                f"Blob creation failed for {path}: {blob_resp.status_code}"
            )
        blob_sha = blob_resp.json()["sha"]
        tree_items.append({
            "path": path,
            "mode": "100644",  # regular file
            "type": "blob",
            "sha": blob_sha,
        })

    # Step 2: Create tree with base_tree = parent commit's tree
    # First get the parent commit's tree SHA
    commit_resp = await client.get(
        f"{GITHUB_API}/repos/{owner}/{repo}/git/commits/{base_sha}"
    )
    if commit_resp.status_code != 200:
        raise ContributionError(f"Get commit failed: {commit_resp.status_code}")
    base_tree_sha = commit_resp.json()["tree"]["sha"]

    tree_resp = await client.post(
        f"{GITHUB_API}/repos/{owner}/{repo}/git/trees",
        json={"base_tree": base_tree_sha, "tree": tree_items},
    )
    if tree_resp.status_code not in (200, 201):
        raise ContributionError(f"Tree creation failed: {tree_resp.status_code}")
    new_tree_sha = tree_resp.json()["sha"]

    # Step 3: Create commit pointing to the new tree
    new_commit_resp = await client.post(
        f"{GITHUB_API}/repos/{owner}/{repo}/git/commits",
        json={
            "message": message,
            "tree": new_tree_sha,
            "parents": [base_sha],
        },
    )
    if new_commit_resp.status_code not in (200, 201):
        raise ContributionError(f"Commit creation failed: {new_commit_resp.status_code}")
    new_commit_sha = new_commit_resp.json()["sha"]

    # Step 4: Update branch ref to point to new commit
    ref_resp = await client.patch(
        f"{GITHUB_API}/repos/{owner}/{repo}/git/refs/heads/{branch}",
        json={"sha": new_commit_sha},
    )
    if ref_resp.status_code != 200:
        raise ContributionError(f"Ref update failed: {ref_resp.status_code}")

    return new_commit_sha


# Keep _commit_file for backward compatibility (single-file commits)
async def _commit_file(
    client: httpx.AsyncClient, owner: str, repo: str,
    path: str, content_b64: str, branch: str, message: str,
) -> None:
    existing_sha = None
    check = await client.get(
        f"{GITHUB_API}/repos/{owner}/{repo}/contents/{path}",
        params={"ref": branch},
    )
    if check.status_code == 200:
        existing_sha = check.json().get("sha")

    payload: dict = {
        "message": message,
        "content": content_b64,
        "branch": branch,
    }
    if existing_sha:
        payload["sha"] = existing_sha

    resp = await client.put(
        f"{GITHUB_API}/repos/{owner}/{repo}/contents/{path}",
        json=payload,
    )
    if resp.status_code not in (200, 201):
        raise ContributionError(f"Commit failed: {resp.status_code}")


async def _create_pr(
    client: httpx.AsyncClient, owner: str, repo: str,
    head: str, base: str, title: str, body: str,
) -> str:
    resp = await client.post(
        f"{GITHUB_API}/repos/{owner}/{repo}/pulls",
        json={"title": title, "body": body, "head": head, "base": base},
    )
    if resp.status_code not in (200, 201):
        raise ContributionError(f"PR creation failed: {resp.status_code}")
    return resp.json().get("html_url", "")
