"""ToolEvolver — the OS evolves its own capabilities over time.

This is the mechanism by which AGOS grows: new tools, channels, and providers
are discovered, generated, tested, and hot-loaded into the running system.

Evolution sources:
1. USAGE PATTERNS  — analyze audit trail to find tool gaps and failures
2. ARXIV PAPERS    — discover new techniques that become tools
3. COMMUNITY       — other AGOS nodes share evolved tools via PRs
4. SELF-REFLECTION — agents request capabilities they don't have

Lifecycle of an evolved tool:
    observe() → propose() → generate() → sandbox() → deploy() → share()

All evolved tools are stored as .py files in .agos/evolved/tools/ and
hot-loaded into the running ToolRegistry without restart.
"""

from __future__ import annotations

import ast
import hashlib
import importlib
import importlib.util
import logging
import os
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from agos.events.bus import EventBus
from agos.policy.audit import AuditTrail
from agos.evolution.sandbox import Sandbox, SandboxResult
from agos.tools.registry import ToolRegistry
from agos.tools.schema import ToolSchema, ToolParameter

_logger = logging.getLogger(__name__)

# Where evolved capabilities live
EVOLVED_TOOLS_DIR = Path(".agos/evolved/tools")
EVOLVED_CHANNELS_DIR = Path(".agos/evolved/channels")
EVOLVED_PROVIDERS_DIR = Path(".agos/evolved/providers")

# Template for generating new tools
_TOOL_TEMPLATE = '''"""Evolved tool: {name} — {description}

Auto-generated by AGOS ToolEvolver on {timestamp}.
Source: {source}
"""

from __future__ import annotations

import asyncio
import json
from typing import Any


TOOL_NAME = "{name}"
TOOL_DESCRIPTION = """{description}"""
TOOL_PARAMETERS = {parameters_json}


async def handler({params_signature}) -> str:
    """Execute the {name} tool."""
{handler_code}
'''

# Template for generating new channels
_CHANNEL_TEMPLATE = '''"""Evolved channel: {name} — {description}

Auto-generated by AGOS ToolEvolver on {timestamp}.
Source: {source}
"""

from __future__ import annotations

from typing import Any
import httpx


CHANNEL_NAME = "{name}"
CHANNEL_DESCRIPTION = """{description}"""
CHANNEL_ICON = "{icon}"


async def send(message_text: str, message_title: str, config: dict[str, Any]) -> dict:
    """Send a message through this channel."""
{handler_code}
    return {{"success": True, "detail": "sent"}}
'''


class ToolNeed:
    """A detected need for a new or improved tool."""

    def __init__(
        self,
        name: str,
        description: str,
        source: str,
        priority: float = 0.5,
        context: dict[str, Any] | None = None,
    ):
        self.name = name
        self.description = description
        self.source = source  # "usage_gap", "failure", "arxiv", "community", "request"
        self.priority = priority
        self.context = context or {}
        self.created_at = datetime.now(timezone.utc)

    def to_dict(self) -> dict:
        return {
            "name": self.name,
            "description": self.description,
            "source": self.source,
            "priority": self.priority,
            "context": self.context,
            "created_at": self.created_at.isoformat(),
        }


class ToolEvolver:
    """Evolves the OS's tool/channel/provider capabilities over time.

    Observe → Propose → Generate → Test → Deploy → Share
    """

    def __init__(
        self,
        event_bus: EventBus,
        audit: AuditTrail,
        tool_registry: ToolRegistry | None = None,
    ):
        self._bus = event_bus
        self._audit = audit
        self._registry = tool_registry
        self._needs: list[ToolNeed] = []
        self._deployed: dict[str, dict] = {}  # name -> metadata
        self._sandbox = Sandbox()

        # Ensure directories exist
        for d in (EVOLVED_TOOLS_DIR, EVOLVED_CHANNELS_DIR, EVOLVED_PROVIDERS_DIR):
            d.mkdir(parents=True, exist_ok=True)

    # ── 1. OBSERVE — detect what's needed ────────────────────

    async def observe_usage(self) -> list[ToolNeed]:
        """Analyze audit trail to find tool gaps and improvement opportunities."""
        needs: list[ToolNeed] = []

        # Check for tool execution failures
        try:
            entries = await self._audit.recent(limit=200)
            failure_counts: dict[str, int] = {}
            tool_usage: dict[str, int] = {}
            missing_requests: list[str] = []

            for entry in entries:
                if entry.action == "tool_execution":
                    tool = entry.detail.split(":")[0] if entry.detail else ""
                    tool_usage[tool] = tool_usage.get(tool, 0) + 1
                    if not entry.success:
                        failure_counts[tool] = failure_counts.get(tool, 0) + 1

                # Detect "tool not found" errors
                if entry.action == "tool_not_found" or (
                    not entry.success and "not found" in (entry.detail or "").lower()
                ):
                    tool_name = entry.detail.split("'")[1] if "'" in (entry.detail or "") else entry.detail or ""
                    missing_requests.append(tool_name)

            # High-failure tools need improvement
            for tool, failures in failure_counts.items():
                total = tool_usage.get(tool, 1)
                failure_rate = failures / total
                if failure_rate > 0.3 and failures >= 3:
                    needs.append(ToolNeed(
                        name=f"{tool}_improved",
                        description=f"Improved version of '{tool}' — current failure rate {failure_rate:.0%}",
                        source="failure",
                        priority=min(0.9, failure_rate),
                        context={"original_tool": tool, "failures": failures, "total": total},
                    ))

            # Missing tools that agents tried to use
            for tool_name in set(missing_requests):
                # Validate: must be a clean identifier, not error text
                clean = tool_name.strip()
                if not clean or len(clean) > 30 or not clean.replace("_", "").replace("-", "").isalnum():
                    continue
                needs.append(ToolNeed(
                    name=clean,
                    description=f"Tool '{clean}' was requested but doesn't exist",
                    source="usage_gap",
                    priority=0.7,
                ))

        except Exception as e:
            _logger.debug("Usage observation failed: %s", e)

        self._needs.extend(needs)
        return needs

    async def observe_arxiv_tools(self, papers: list[dict]) -> list[ToolNeed]:
        """Extract tool ideas from arxiv papers."""
        needs = []
        tool_keywords = {
            "retrieval": ("rag_retrieve", "Retrieve and rank documents using RAG techniques"),
            "web browsing": ("web_browse", "Navigate and extract content from web pages"),
            "code generation": ("code_generate", "Generate code from natural language description"),
            "code review": ("code_review", "Analyze code for bugs, style, and improvements"),
            "summarization": ("summarize", "Summarize long text, documents, or conversations"),
            "translation": ("translate", "Translate text between languages"),
            "image analysis": ("image_analyze", "Analyze and describe image content"),
            "pdf extraction": ("pdf_extract", "Extract text and data from PDF files"),
            "api discovery": ("api_discover", "Discover and document API endpoints"),
            "test generation": ("test_generate", "Generate unit tests for code"),
            "data pipeline": ("data_pipeline", "Process and transform data through a pipeline"),
            "knowledge graph": ("kg_query", "Query and update knowledge graphs"),
            "embedding": ("embed_text", "Generate text embeddings for similarity search"),
            "classification": ("classify", "Classify text into categories"),
            "sentiment": ("sentiment_analyze", "Analyze sentiment of text"),
            "entity extraction": ("extract_entities", "Extract named entities from text"),
        }

        for paper in papers:
            title = paper.get("title", "").lower()
            abstract = paper.get("abstract", "").lower()
            combined = f"{title} {abstract}"

            for keyword, (tool_name, description) in tool_keywords.items():
                if keyword in combined:
                    # Check if we already have this tool
                    if self._registry and tool_name in [t.name for t in self._registry.list_tools()]:
                        continue
                    needs.append(ToolNeed(
                        name=tool_name,
                        description=description,
                        source="arxiv",
                        priority=0.5,
                        context={"paper_title": paper.get("title", ""), "paper_id": paper.get("id", "")},
                    ))

        self._needs.extend(needs)
        return needs

    def request_tool(self, name: str, description: str) -> ToolNeed:
        """Agents can explicitly request tools they need."""
        need = ToolNeed(
            name=name,
            description=description,
            source="request",
            priority=0.8,
        )
        self._needs.append(need)
        return need

    # ── 2. GENERATE — create tool code ───────────────────────

    # Built-in tools that the OS already has — evolution should activate, not regenerate
    _BUILTIN_TOOLS = {
        "docker": "agos.tools.docker_tool",
        "docker-compose": "agos.tools.docker_tool",
        "browser": "agos.tools.browser_tool",
        "playwright": "agos.tools.browser_tool",
    }

    async def generate_tool(self, need: ToolNeed, llm_provider=None) -> str | None:
        """Generate or activate a tool for a need.

        Priority:
        1. Check if tool already registered in the registry (exact or fuzzy match)
        2. If a built-in tool exists for this need, activate it
        3. Try connecting an MCP server that provides the capability
        4. Use LLM to generate code (with env + codebase context)
        5. Fall back to template-based generation
        """
        # 0. Check if tool is already registered (avoid duplicate work)
        if self._registry:
            existing = [t.name for t in self._registry.list_tools()]
            if need.name in existing:
                _logger.debug("Tool '%s' already registered, skipping", need.name)
                return None

        # 1. Check if we already have a built-in for this
        # Use both exact match AND fuzzy match for builtin detection
        builtin_module = self._BUILTIN_TOOLS.get(need.name)
        if not builtin_module:
            # Fuzzy: check if any builtin keyword appears as a whole word
            import re as _re
            need_text = f"{need.name} {need.description}".lower()
            for builtin_name, module in self._BUILTIN_TOOLS.items():
                if _re.search(r'\b' + _re.escape(builtin_name) + r'\b', need_text):
                    builtin_module = module
                    break

        if builtin_module:
            _logger.info("Evolution: activating built-in tool '%s' from %s", need.name, builtin_module)
            await self._bus.emit("evolution.builtin_activated", {
                "tool": need.name, "module": builtin_module,
                "reason": need.description[:100],
            }, source="tool_evolver")
            return None  # No code to generate, tool already exists

        # 2. Try MCP server discovery (if available)
        mcp_code = await self._try_mcp_discovery(need)
        if mcp_code:
            return mcp_code

        # 3. LLM generation (with environment + codebase context)
        if llm_provider:
            return await self._generate_with_llm(need, llm_provider)

        # 4. Template fallback
        return self._generate_from_template(need)

    async def _try_mcp_discovery(self, need: ToolNeed) -> str | None:
        """Try to find an MCP server that provides the needed capability."""
        # Known MCP servers for common needs
        _MCP_SERVERS = {
            "database": {"command": "npx", "args": ["-y", "@modelcontextprotocol/server-sqlite"]},
            "filesystem": {"command": "npx", "args": ["-y", "@modelcontextprotocol/server-filesystem"]},
            "github": {"command": "npx", "args": ["-y", "@modelcontextprotocol/server-github"]},
            "memory": {"command": "npx", "args": ["-y", "@modelcontextprotocol/server-memory"]},
        }
        server_config = _MCP_SERVERS.get(need.name)
        if server_config:
            _logger.info("Evolution: found MCP server for '%s'", need.name)
            await self._bus.emit("evolution.mcp_discovered", {
                "tool": need.name, "server": server_config,
            }, source="tool_evolver")
            # Return a wrapper that connects the MCP server
            # The actual connection happens via MCPManager at runtime
            return None  # MCP connection handled separately
        return None

    async def _generate_with_llm(self, need: ToolNeed, llm) -> str | None:
        """Use LLM to reason about what tool to build and generate it.

        Unlike keyword matching, this gives the LLM:
        - The demand context (what failed and why)
        - The environment (what's available: Docker? apt? pip? Node?)
        - The codebase structure (what modules exist)
        So it can design a tool that actually works in THIS environment.
        """
        # Gather environment context
        env_summary = ""
        try:
            from agos.environment import EnvironmentProbe
            env_summary = EnvironmentProbe.summary()
        except Exception:
            env_summary = "(environment unknown)"

        # Gather codebase context
        codebase = ""
        try:
            from agos.evolution.codebase_map import read_codebase_map
            codebase = read_codebase_map()[:1500]
        except Exception:
            pass

        # Build demand context from the need
        demand_detail = ""
        if need.context:
            demand_ctx = need.context
            if demand_ctx.get("demand"):
                demand_detail = f"\nOriginal demand: {demand_ctx['demand']}"
            if demand_ctx.get("hint"):
                demand_detail += f"\nImplementation hint: {demand_ctx['hint']}"
            if demand_ctx.get("environment"):
                demand_detail += f"\nEnvironment detail: {demand_ctx['environment'][:300]}"

        prompt = f"""You are the evolution engine of OpenSculpt, an agentic OS.
A sub-agent needs a tool that doesn't exist yet. Design and generate it.

TOOL NEEDED:
  Name: {need.name}
  Description: {need.description}
  Source: {need.source}
  Priority: {need.priority}
{demand_detail}

ENVIRONMENT (what's available to use):
{env_summary}

EXISTING MODULES:
{codebase if codebase else "(unknown)"}

Think step by step:
1. What EXACTLY should this tool do?
2. Given the environment, what's the BEST implementation approach?
   - If Docker is available, use subprocess to call docker CLI
   - If apt/pip available, use installed packages
   - If only Python stdlib, use that
3. What parameters does it need?
4. How should it handle errors?

Requirements:
- Function MUST be async and return a string result
- Import only: stdlib + httpx + json + asyncio + subprocess
- Handle errors gracefully — return error strings, don't raise
- Under 60 lines of actual code
- Include proper type hints

Return ONLY valid Python code. Format:

```python
async def handler(param1: str, param2: str = "") -> str:
    \"\"\"What this tool does.\"\"\"
    # implementation using what's actually available
    return "result"
```"""

        try:
            from agos.llm.base import LLMMessage
            resp = await llm.complete(
                messages=[LLMMessage(role="user", content=prompt)],
                system="You are a tool generator. Output only valid Python code. No markdown explanation outside the code block.",
                max_tokens=1500,
            )
            response = resp.content or ""
            # Extract code block
            import re
            match = re.search(r"```python\s*\n(.*?)```", response, re.DOTALL)
            if match:
                return match.group(1).strip()
            # Try without code fences
            if "async def handler" in response:
                start = response.index("async def handler")
                return response[start:].strip()
        except Exception as e:
            _logger.warning("LLM tool generation failed: %s", e)

        return self._generate_from_template(need)

    def _generate_from_template(self, need: ToolNeed) -> str:
        """Generate tool code from templates (no LLM needed)."""
        # Common tool patterns
        patterns: dict[str, tuple[list[dict], str, str]] = {
            "web": (
                [{"name": "url", "description": "URL to fetch"}],
                "url: str",
                '    import httpx\n    async with httpx.AsyncClient(timeout=15) as c:\n        r = await c.get(url)\n        return f"HTTP {r.status_code}\\n{r.text[:3000]}"',
            ),
            "file": (
                [{"name": "path", "description": "File path"}],
                "path: str",
                '    from pathlib import Path\n    p = Path(path)\n    if not p.exists():\n        return f"Not found: {path}"\n    return p.read_text(encoding="utf-8", errors="replace")[:5000]',
            ),
            "shell": (
                [{"name": "command", "description": "Command to run"}],
                "command: str",
                '    import asyncio, subprocess\n    proc = await asyncio.create_subprocess_shell(\n        command, stdout=subprocess.PIPE, stderr=subprocess.PIPE)\n    out, err = await asyncio.wait_for(proc.communicate(), timeout=30)\n    return out.decode(errors="replace")[:3000]',
            ),
            "data": (
                [{"name": "input", "description": "Input data"}],
                "input: str",
                '    import json\n    try:\n        data = json.loads(input)\n        return json.dumps(data, indent=2)[:3000]\n    except Exception as e:\n        return f"Error: {e}"',
            ),
        }

        # Select pattern based on need description
        desc_lower = need.description.lower()
        if any(w in desc_lower for w in ("url", "web", "http", "fetch", "scrape", "api")):
            pattern_key = "web"
        elif any(w in desc_lower for w in ("file", "read", "write", "path", "directory")):
            pattern_key = "file"
        elif any(w in desc_lower for w in ("command", "shell", "exec", "run", "process")):
            pattern_key = "shell"
        else:
            pattern_key = "data"

        params, sig, code = patterns[pattern_key]

        return _TOOL_TEMPLATE.format(
            name=need.name,
            description=need.description,
            timestamp=datetime.now(timezone.utc).isoformat(),
            source=need.source,
            parameters_json=params,
            params_signature=sig,
            handler_code=code,
        )

    # ── 3. TEST — sandbox the generated code ─────────────────

    async def test_tool(self, code: str, tool_name: str) -> SandboxResult:
        """Run the generated tool code through sandbox validation."""
        return await asyncio.get_event_loop().run_in_executor(
            None, self._sandbox.validate, code,
        )

    # ── 4. DEPLOY — hot-load into running system ─────────────

    async def deploy_tool(self, code: str, need: ToolNeed) -> bool:
        """Write the tool file and hot-load it into the registry.

        Applies linting gate (SWE-agent pattern) before writing:
        1. ast.parse() — reject syntax errors
        2. Dangerous import check — reject os.system, eval, exec
        """
        # ── Linting gate: reject broken code before writing to disk ──
        try:
            import ast
            ast.parse(code)
        except SyntaxError as e:
            _logger.warning("Linting gate REJECTED %s: syntax error at line %s: %s",
                            need.name, e.lineno, e.msg)
            return False

        # Check for dangerous patterns
        _dangerous = {"os.system", "subprocess.call(", "eval(", "exec(", "__import__"}
        for pattern in _dangerous:
            if pattern in code:
                _logger.warning("Linting gate REJECTED %s: dangerous pattern '%s'",
                                need.name, pattern)
                return False

        file_path = EVOLVED_TOOLS_DIR / f"{need.name}.py"

        # Don't overwrite if unchanged
        code_hash = hashlib.sha256(code.encode()).hexdigest()[:12]
        if file_path.exists():
            existing_hash = hashlib.sha256(file_path.read_text().encode()).hexdigest()[:12]
            if existing_hash == code_hash:
                _logger.debug("Tool %s unchanged, skipping deploy", need.name)
                return True

        # Write the file
        file_path.write_text(code, encoding="utf-8")
        _logger.info("Wrote evolved tool: %s (%s)", need.name, file_path)

        # Hot-load into registry
        if self._registry:
            loaded = self._load_tool_from_file(file_path)
            if loaded:
                self._deployed[need.name] = {
                    "file": str(file_path),
                    "hash": code_hash,
                    "source": need.source,
                    "deployed_at": datetime.now(timezone.utc).isoformat(),
                    "description": need.description,
                }
                await self._bus.emit("evolution.tool_deployed", {
                    "tool": need.name,
                    "source": need.source,
                    "description": need.description,
                }, source="tool_evolver")
                return True

        return False

    def _load_tool_from_file(self, file_path: Path) -> bool:
        """Import a tool .py file and register it."""
        try:
            module_name = f"evolved_tool_{file_path.stem}"
            spec = importlib.util.spec_from_file_location(module_name, file_path)
            if not spec or not spec.loader:
                return False
            module = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(module)

            # Extract tool metadata
            tool_name = getattr(module, "TOOL_NAME", file_path.stem)
            description = getattr(module, "TOOL_DESCRIPTION", "Evolved tool")
            params_raw = getattr(module, "TOOL_PARAMETERS", [])
            handler = getattr(module, "handler", None)

            if not handler:
                _logger.warning("Evolved tool %s has no handler function", file_path)
                return False

            # Build schema
            parameters = []
            for p in params_raw:
                if isinstance(p, dict):
                    parameters.append(ToolParameter(
                        name=p.get("name", "input"),
                        type=p.get("type", "string"),
                        description=p.get("description", ""),
                        required=p.get("required", True),
                    ))

            schema = ToolSchema(name=tool_name, description=description, parameters=parameters)
            self._registry.register(schema, handler)
            _logger.info("Hot-loaded evolved tool: %s", tool_name)
            return True

        except Exception as e:
            _logger.warning("Failed to load evolved tool %s: %s", file_path, e)
            return False

    # ── 5. FULL CYCLE — run the complete evolution ───────────

    async def evolve_cycle(self, llm_provider=None, papers: list[dict] | None = None) -> dict:
        """Run one full tool evolution cycle.

        Returns summary of what was discovered, generated, and deployed.
        """
        summary = {
            "needs_discovered": 0,
            "tools_generated": 0,
            "tools_passed_sandbox": 0,
            "tools_deployed": 0,
            "deployed_names": [],
            "errors": [],
        }

        # 1. Observe — combine audit-based + arxiv + direct requests
        usage_needs = await self.observe_usage()
        if papers:
            arxiv_needs = await self.observe_arxiv_tools(papers)
        else:
            arxiv_needs = []

        # Include any directly requested tools (from demand signals)
        all_needs = self._needs + usage_needs + arxiv_needs
        self._needs = []  # Clear after consuming
        summary["needs_discovered"] = len(all_needs)

        if not all_needs:
            return summary

        # Sort by priority, take top 3 per cycle
        all_needs.sort(key=lambda n: -n.priority)
        batch = all_needs[:3]

        for need in batch:
            try:
                # 2. Generate (or activate builtin)
                code = await self.generate_tool(need, llm_provider)
                if code is None:
                    # Check if it was a builtin activation (not a real failure)
                    if need.name in self._BUILTIN_TOOLS:
                        summary["tools_deployed"] += 1
                        summary["deployed_names"].append(need.name)
                        _logger.info("Builtin tool '%s' activated by evolution", need.name)
                        continue
                    summary["errors"].append(f"Generation failed for {need.name}")
                    continue
                summary["tools_generated"] += 1

                # 3. Test
                result = await self.test_tool(code, need.name)
                if not result.passed:
                    summary["errors"].append(f"Sandbox failed for {need.name}: {result.reason}")
                    continue
                summary["tools_passed_sandbox"] += 1

                # 4. Deploy
                deployed = await self.deploy_tool(code, need)
                if deployed:
                    summary["tools_deployed"] += 1
                    summary["deployed_names"].append(need.name)

            except Exception as e:
                summary["errors"].append(f"{need.name}: {e}")

        await self._bus.emit("evolution.tools_evolved", summary, source="tool_evolver")
        return summary

    # ── 6. LOAD EXISTING — restore from disk on boot ─────────

    async def load_existing(self) -> int:
        """Load all previously evolved tools from disk."""
        count = 0
        if not EVOLVED_TOOLS_DIR.exists():
            return 0

        for file_path in sorted(EVOLVED_TOOLS_DIR.glob("*.py")):
            if file_path.name.startswith("_"):
                continue
            if self._load_tool_from_file(file_path):
                count += 1

        if count:
            _logger.info("Loaded %d evolved tools from %s", count, EVOLVED_TOOLS_DIR)
        return count

    # ── Status ───────────────────────────────────────────────

    def status(self) -> dict:
        return {
            "deployed_tools": len(self._deployed),
            "pending_needs": len(self._needs),
            "tools": self._deployed,
            "needs": [n.to_dict() for n in self._needs[-20:]],
        }


# Needed for sandbox validation
import asyncio  # noqa: E402 (used in test_tool)
