"""ResearchDaemon — autonomous research on any topic.

Give it a topic and it searches arxiv + web, compiles a markdown report.
Runs as a one-shot hand: start it, it researches, delivers a report, done.

Usage from dashboard:
    Start "researcher" with config: {"topic": "retrieval augmented generation"}
"""

from __future__ import annotations

import logging
from datetime import datetime, timezone

import httpx

from agos.daemons.base import Daemon, DaemonResult

_logger = logging.getLogger(__name__)

# Arxiv categories to search
_CS_CATS = "cs.AI+OR+cat:cs.CL+OR+cat:cs.LG+OR+cat:cs.SE+OR+cat:cs.MA"


class ResearchDaemon(Daemon):
    name = "researcher"
    description = "Research any topic — searches arxiv, compiles a report"
    icon = "🔍"
    one_shot = True

    async def tick(self) -> None:
        topic = self.config.get("topic", "").strip()
        if not topic:
            self.add_result(DaemonResult(
                daemon_name=self.name, success=False,
                summary="No topic provided. Set config: {\"topic\": \"your topic\"}",
            ))
            return

        max_papers = self.config.get("max_papers", 10)
        await self.emit("searching", {"topic": topic, "max_papers": max_papers})

        papers = await self._search_arxiv(topic, max_papers)
        if not papers:
            self.add_result(DaemonResult(
                daemon_name=self.name, success=False,
                summary=f"No papers found for: {topic}",
            ))
            return

        report = self._compile_report(topic, papers)

        await self.emit("report_ready", {
            "topic": topic,
            "papers_found": len(papers),
            "report_length": len(report),
        })

        self.add_result(DaemonResult(
            daemon_name=self.name,
            success=True,
            summary=f"Found {len(papers)} papers on '{topic}'",
            data={"report": report, "papers": papers},
        ))

    async def _search_arxiv(self, topic: str, max_results: int) -> list[dict]:
        """Search arxiv for papers matching the topic."""
        query = topic.replace(" ", "+")
        url = (
            f"https://export.arxiv.org/api/query?"
            f"search_query=(ti:{query}+OR+abs:{query})"
            f"+AND+(cat:{_CS_CATS})"
            f"&max_results={max_results}"
            f"&sortBy=submittedDate&sortOrder=descending"
        )

        papers = []
        try:
            async with httpx.AsyncClient(timeout=30) as client:
                resp = await client.get(url)
                resp.raise_for_status()

            import xml.etree.ElementTree as ET
            ns = {"atom": "http://www.w3.org/2005/Atom"}
            root = ET.fromstring(resp.text)

            for entry in root.findall("atom:entry", ns):
                title = entry.findtext("atom:title", "", ns).strip().replace("\n", " ")
                abstract = entry.findtext("atom:summary", "", ns).strip().replace("\n", " ")
                arxiv_id = entry.findtext("atom:id", "", ns).split("/abs/")[-1]
                published = entry.findtext("atom:published", "", ns)[:10]
                authors = [
                    a.findtext("atom:name", "", ns)
                    for a in entry.findall("atom:author", ns)
                ]

                papers.append({
                    "title": title,
                    "abstract": abstract[:500],
                    "arxiv_id": arxiv_id,
                    "published": published,
                    "authors": authors[:5],
                    "url": f"https://arxiv.org/abs/{arxiv_id}",
                })
        except Exception as e:
            _logger.warning("Arxiv search failed for '%s': %s", topic, e)

        return papers

    def _compile_report(self, topic: str, papers: list[dict]) -> str:
        """Compile papers into a readable markdown report."""
        now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        lines = [
            f"# Research Report: {topic}",
            f"*Generated by AGOS ResearchDaemon on {now}*",
            f"*{len(papers)} papers found on arxiv*",
            "",
            "---",
            "",
        ]

        for i, p in enumerate(papers, 1):
            authors = ", ".join(p["authors"][:3])
            if len(p["authors"]) > 3:
                authors += f" et al. ({len(p['authors'])} authors)"

            lines.extend([
                f"## {i}. {p['title']}",
                f"**Authors:** {authors}",
                f"**Published:** {p['published']} | [arxiv]({p['url']})",
                "",
                f"> {p['abstract'][:300]}{'...' if len(p['abstract']) > 300 else ''}",
                "",
                "---",
                "",
            ])

        lines.extend([
            "## Summary",
            f"Found {len(papers)} recent papers related to **{topic}**.",
            "",
            "### Key themes:",
        ])

        # Simple keyword frequency analysis
        all_text = " ".join(p["title"] + " " + p["abstract"] for p in papers).lower()
        keywords = {}
        for word in ["learning", "model", "agent", "memory", "retrieval",
                     "generation", "optimization", "transformer", "attention",
                     "knowledge", "reasoning", "planning", "benchmark",
                     "framework", "architecture", "training", "inference",
                     "embedding", "graph", "policy", "reward"]:
            count = all_text.count(word)
            if count >= 3:
                keywords[word] = count

        for kw, count in sorted(keywords.items(), key=lambda x: -x[1])[:8]:
            lines.append(f"- **{kw}** (mentioned {count} times)")

        return "\n".join(lines)
